config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  patch '/update_avatar', to: 'users#update_avatar', as: :update_avatar
  patch '/update_cover', to: 'users#update_cover', as: :update_cover
  resources :users, only: [:index, :show] 
  resources :posts do
    post '/like', to: 'reactions#like', as: :like_action
    post '/dislike', to: 'reactions#dislike', as: :dislike_action
    resources :comments do
      post '/support', to: 'votes#support', as: :support_action
      post '/nonsupport', to: 'votes#nonsupport', as: :nonsupport_action
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :votes, dependent: :destroy

  def supports
    self.votes.filter{ |vote| vote.support }.length
  end

  def nonsupports
    self.votes.filter{ |vote| vote.nonsupport }.length
  end

  def supported(user)
    vote = votes.find_by(user_id: user.id)
    vote.nil? ? false : vote.support
  end

  def nonsupported(user)
    vote = votes.find_by(user_id: user.id)
    vote.nil? ? false : vote.nonsupport
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  validates :user_id, presence: true
  validates :text, presence: true, length: { in: 1..200 }

  def likes
    self.reactions.filter{ |reaction| reaction.like }.length
  end

  def dislikes
    self.reactions.filter{ |reaction| reaction.dislike }.length
  end

  def liked(user)
    reaction = reactions.find_by(user_id: user.id)
    reaction.nil? ? false : reaction.like
  end

  def disliked(user)
    reaction = reactions.find_by(user_id: user.id)
    reaction.nil? ? false : reaction.dislike
  end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
         
      has_many :posts, dependent: :destroy
      has_many :reactions, dependent: :destroy
      has_many :comments, dependent: :destroy
      has_many :votes, dependent: :destroy


      has_one_attached :avatar
      has_one_attached :cover_picture

      validates :username, presence: true, uniqueness: true, length: { in: 3..15 }
      validates :email, presence: true, uniqueness: true, format: Devise.email_regexp
      validates :gender, presence: true
      validates :bio, presence: true, length: { maximum: 200 }
      validates :password, presence: true, length: { in: 6..20 }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      before_action :configure_permitted_parameters, if: :devise_controller?

      protected

      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar, :cover_picture, :fullname, :bio, :gender])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar, :cover_picture, :fullname, :bio, :gender])
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
      def create
        @comment = current_user.comments.new(post_id: params[:post_id], text: params[:comment][:text])
    
        @comment.save
        ActionCable.server.broadcast "comments_channel",
                                      comment: @comment,
                                      user: current_user,
                                      post: @comment.post,
                                      n_comments: @comment.post.comments.length
      end
    
      def destroy
        Comment.find(params[:id]).destroy
      end
    
      private
    
      def comment_params
        params.require(:comment).permit(:text)
      end
    end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.all.order('created_at DESC')
    @post = Post.new
   end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to request.referrer, notice: 'Your post was created! yahoo!'
    else
      redirect_to request.referrer, alert: 'Sorry, post was not created, for some reason'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    if Post.find(params[:id]).update(post_params)
      redirect_to request.referrer, notice: 'post updated'
    else
      redirect_to request.referrer, alert: 'some dumb thing happened'
    end
  end
  
  def destroy
    if Post.find(params[:id]).destroy
      redirect_to request.referrer, notice: 'post deleted'
    else
      redirect_to request.referrer, alert: 'some dumb thing happened'
    end
  end

  private

  def post_params
    params.require(:post).permit(:text, :image)
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

  def like
    reaction = Reaction.find_by(user_id: current_user.id, post_id: params[:post_id])

    unless reaction.nil?
      if reaction.like
        reaction.destroy
      else  
        update(reaction, true)
      end
    else
      save(true)
    end
  end

  def dislike
    reaction = Reaction.find_by(user_id: current_user.id, post_id: params[:post_id])

    unless reaction.nil?
      if reaction.dislike
        reaction.destroy
      else  
        update(reaction, false)
      end
    else
      save(false)
    end
  end

  def save(like)
    post = Post.find(params[:post_id])
    reaction = post.reactions.build
    reaction.user = current_user
    reaction.like = like
    reaction.dislike = !like
    reaction.save
  end

  def update(reaction, like)
    reaction.like = like
    reaction.dislike = !like
    reaction.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @friends = current_user.friends
    @non_friends = User.all.filter{ |user| 
      !@friends.include?(user) &&
      current_user != user &&
      !current_user.pending_friends.include?(user) &&
      !current_user.friend_requests.include?(user)
    }
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts.order(created_at: :desc)
  end

  def update_avatar
    @user = current_user

    if @user.update(avatar: params[:user][:avatar])
      redirect_to user_path(current_user), notice: 'avatar was updated successfully.'
    else
      redirect_to user_path(current_user), alert: 'avatar wasn\'t updated for some reason.'
    end
  end
  
  def update_cover
    @user = current_user

    if @user.update(cover_picture: params[:user][:cover_picture])
      redirect_to user_path(current_user), notice: 'cover image was updated successfully.'
    else
      redirect_to user_path(current_user), alert: 'cover iamge wasn\'t updated for some reason.'
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

      def support
        vote = Vote.find_by(user_id: current_user.id, comment_id: params[:comment_id])
    
        unless vote.nil?
          if vote.support
            vote.destroy
          else  
            update(vote, true)
          end
        else
          save(true)
        end
      end
    
      def nonsupport
        vote = Vote.find_by(user_id: current_user.id, comment_id: params[:comment_id])
    
        unless vote.nil?
          if vote.nonsupport
            vote.destroy
          else  
            update(vote, false)
          end
        else
          save(false)
        end
      end
    
      def save(support)
        comment = Comment.find(params[:comment_id])
        vote = comment.votes.build
        vote.user = current_user
        vote.support = support
        vote.nonsupport = !support
        vote.save
      end
    
      def update(vote, support)
        vote.support = support
        vote.nonsupport = !support
        vote.save
      end
    end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_user_image.html.erb
<% if user %>
  <% if user.avatar.attached? %>
    <%= image_tag user.avatar, class: 'profile-image'%>
  <% else %>
      <%= image_tag "https://api.multiavatar.com/#{user.username}.png", class: 'profile-image' %>
  <% end %>
<% else %>
  <%= image_tag 'https://img2.thejournal.ie/inline/1881369/original/?width=630&version=1881369', class: 'profile-image' %>
<% end %>

app/views/application/_user_profile.html.erb
<% if user_signed_in? %>
  <div class="profile-container">
    <div class="text-center">
      <div class="avatar">
        <%= link_to user_path(current_user) do %>
          <%= render partial: 'user_image', locals: { user: current_user } %>
        <% end %>
      </div>
      <div class="username"><%= current_user.username %></div>
    </div>
    <div class="profile_links">
      <%= link_to root_path,class: 'feeds' do %>
        <i class="fas fa-home"></i>
        Feeds
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<div class="comment-container">
  <div class="comment">
    <div class="user-avatar">
      <%= link_to user_path(comment.user) do %>
        <%= render partial: 'user_image', locals: { user: comment.user } %>
      <% end %>
    </div>
    <div class="comment-body">
      <div class="flex">
        <span class='user-name'><%= comment.user.username %></span>
        <%= comment.text %>
      </div>
      <div class="vote-container">
          <% if user_signed_in? %>
            <div class="supports">
              <span class="<% if comment.supported(current_user) %><%= 'has-text-base' %><% end %>"><%= comment.supports %></span>
              <%= link_to post_comment_support_action_path(:comment_id => comment.id, :post_id => comment.post.id), method: :post do %>
              <i class="fas fa-thumbs-up <% if comment.supported(current_user) %><%= 'has-text-base' %><% end %>"></i>
              <% end %>
            </div>
                    
            <div class="nonsupports">
              <span class="<% if comment.nonsupported(current_user) %><%= 'has-text-base' %><% end %>"><%= comment.nonsupports %></span>

              <%= link_to post_comment_nonsupport_action_path(:comment_id => comment.id, :post_id => comment.post.id), method: :post do %>
              <i class="fas fa-thumbs-down <% if comment.nonsupported(current_user) %><%= 'has-text-base' %><% end %>"></i> 
              <% end %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
  <div class="comment-action">
    <% if comment.user == current_user %>
      <%= link_to  '<i class="fa fa-trash"></i>'.html_safe, post_comment_path(post ,comment), method: :delete %>
    <% end %>
    <span class="comment-date"><%= time_ago_in_words(comment.created_at) %>, ago</span>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="comment-form">
  <div class="comment-avatar">
    <%= render partial: 'user_image', locals: { user: current_user } %>
  </div>
  <%= simple_form_for current_user.comments.new, url: post_comments_path(post) do |f| %>
    <%= f.input_field :text, placeholder: 'Any excellent idea of naming?', class: "textarea"%>
    <%= f.button :submit, 'Comment', class: 'button is-success is-small' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NamingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="user-id" data-user-id="<%= current_user.try(:id) %>"></div>
    <% if current_user %>
      <div id='user-avatar' hidden='true'>
        <%= render partial: 'user_image', locals: { user: current_user } %>
      </div>
    <% end %>
      <nav class="nav-bar md-display-none">
        <div class="nav-bar-content">
          <a class="logo-container" href="/">
            <span class="logo-text">
              Naming Your Life
            </span>
          </a>
        </div>
        <div class="shrink-non">
          <% if user_signed_in? %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign In', user_session_path, class: "sign-link" %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "sign-link" %>
          <% end %>
        </div>
      </nav>
    <main class="main-container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<div class="columns is-centered column-style">
  <div class="column is-one-fifth mt">
    <%= render 'user_profile' %>
  </div>
  <div class= "column is-three-fifths">
    <div class="timeline-container">
      <h1 class="title is-2 has-text-base has-text-centered"> Home </h1>
      <% if user_signed_in? %>
        <div class="post-form">

          <%= simple_form_for @post do |f| %>
            <%= f.text_area :text, label: 'name', placeholder: 'Looking for some naming idea?', class:"textarea post-area" %>
            <div id="image-upload-js" class="file has-name">
              <label class="file-label">
                <%= f.file_field :image %>
                <span class="file-cta">
                  <span class="file-icon">
                    <i class="fa fa-image"></i>
                  </span>
                  <span class="file-name has-text-grey-light">
                    No file uploaded
                  </span>
                </span>
              </label>
            </div>
            <%= f.button :submit, 'Post' ,class: 'button is-medium btn-base' %>
          <% end %>
        </div>
      <% end %>

      <div class="posts-container">
        <% @posts.each do |post| %>
          <div id="post-<%= post.id %>" class="box">
            <div class="poster-identifier">
              <div class="poster-info">
                <%= link_to user_path(post.user), class: "has-text-black underline" do %>
                  <div class="image-wrapper">
                    <%= render partial: 'user_image', locals: { user: post.user } %>
                  </div>
                <% end %>
                <div class="post-data">
                  <%= link_to user_path(post.user), class: "has-text-black underline" do %>
                    <span class="name"><%= post.user.username %></span>
                  <% end %>
                  <span class="username">@<%= post.user.username %></span>
                  <span class="date">
                    <%= time_ago_in_words(post.created_at) %>
                  </span>
                </div>
              </div>
              <% if current_user == post.user %>
                <div class="post-actions">
                  <div class="dropdown">
                    <div class="dropdown-trigger">
                      <a class="post-action-container"><i class="fas fa-ellipsis-v"></i></a>
                    </div>
                    <div class="dropdown-menu" id="dropdown-menu4" role="menu">
                      <div class="dropdown-content post-action-menu">
                      <%= link_to  "Edit", edit_post_path(post), class: "dropdown-item" %>
                      <%= link_to  "Delete", post_path(post), method: :delete, class: "dropdown-item" %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>

            </div>

            <div class="post-text">
              <%= post.text %>
            </div>

            <% if post.image.attached? %>
              <div class="post-image">
                <%= image_tag post.image %>
              </div>
            <% end %>

            <div class="reaction-container">
              <% if user_signed_in? %>
                <div class="likes">
                  <span class="<% if post.liked(current_user) %><%= 'has-text-base' %><% end %>"><%= post.likes %></span>
                  <%= link_to post_like_action_path(post), method: :post do %>
                    <i class="fas fa-thumbs-up <% if post.liked(current_user) %><%= 'has-text-base' %><% end %>"></i>
                  <% end %>
                </div>
                <div class="dislikes">
                  <span class="<% if post.disliked(current_user) %><%= 'has-text-base' %><% end %>"><%= post.dislikes %></span>

                  <%= link_to post_dislike_action_path(post), method: :post do %>
                    <i class="fas fa-thumbs-down <% if post.disliked(current_user) %><%= 'has-text-base' %><% end %>"></i> 
                  <% end %>
                </div>
              <% end %>
              <div class="comments">
                <span><%= post.comments.length %></span> 
                <% if post.comments.length == 1  %>
                  Comment
                <% else %>
                  Comments
                <% end %>
              </div>
            </div>
            <div class="comments-container">
              <% post.comments.each do |comment| %>
                <%= render partial: 'comments/comment', locals: { post: post, comment: comment } %>
              <% end %>
            </div>

            <% if user_signed_in? %>
              <%= render partial: 'comments/form', locals: { post: post } %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div id="avatar-modal" class="modal">
  <div id="avatar-modal-background" class="modal-background"></div>
  <div class="modal-content avatar-edit-form">
    <h1 class="title is-3">Update</h1>

    <%= simple_form_for @user, url: update_avatar_path do |f| %>
      <div class="update-image">
        <%= render partial: 'user_image', locals: { user: current_user } %>
      </div>
      <div id="image-upload-js-3" class="file has-name">
        <label class="file-label">
          <%= f.file_field :avatar, class: 'file-input' %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fa fa-image"></i>
            </span>
            <span class="file-name has-text-grey-light">
              select new avatar
            </span>
          </span>
        </label>
      </div>
      <%= f.button :submit, 'Update', class: 'button is-base' %>
    <% end %>
  </div>
  <button id="avatar-modal-close" class="modal-close is-large" aria-label="close"></button>
</div>

<div id="cover-modal" class="modal">
  <div id="cover-modal-background" class="modal-background"></div>
  <div class="modal-content cover-edit-form">
    <h1 class="title is-3">Update Cover Picture</h1>

    <%= simple_form_for @user, url: update_cover_path do |f| %>
      <div class="cover-picture">
        <% if @user.cover_picture.attached?  %>
          <%= image_tag @user.cover_picture, class: 'cover-image' %>
        <% else %>
          <%= image_tag 'https://images.freecreatives.com/wp-content/uploads/2017/01/m.jpg', class: 'cover-image' %>
        <% end %>
      </div>
      <div id="image-upload-js-4" class="file has-name">
        <label class="file-label">
          <%= f.file_field :cover_picture, class: 'file-input' %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fa fa-image"></i>
            </span>
            <span class="file-name has-text-grey-light">
              select new cover
            </span>
          </span>
        </label>
      </div>
      <%= f.button :submit, 'Update avatar', class: 'button is-base' %>
    <% end %>
  </div>
  <button id="cover-modal-close" class="modal-close is-large" aria-label="close"></button>
</div>
<div class= "column is-four-fifths">
  <div class='user-info-container'>
    <div class="cover-picture">
      <% if @user.cover_picture.attached?  %>
        <%= image_tag @user.cover_picture, class: 'cover-image' %>
      <% else %>
        <%= image_tag 'https://images.unsplash.com/photo-1458682625221-3a45f8a844c7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80', class: 'cover-image' %>
      <% end %>
      <% if current_user == @user %>
        <span id='show-cover-modal' class="image-link cover-button">Change Cover</span>
      <% end %>
    </div>
    <div class="profile-show-container">
      <div class="avatar">
        <%= render partial: 'user_image', locals: { user: @user } %>
        <% if current_user == @user %>
          <span id='show-avatar-modal' class="image-link">Edit</span>
        <% end %>
      </div>
      <div class="user-info">
       <span class="username">@<%= @user.username %></span>
        <% if current_user == @user %>
          <div class="friend-status">
            <div class="friend-request-action">
              <%= link_to "Edit Profile", edit_user_registration_path, class: 'button is-small is-link' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="columns is-centered">
    <div class="timeline-container column is-four-fifths">
      <div class="columns">
        <div class="column <%= 'is-two-fifths' if @user == current_user %>">
          <div class="box profile-intro">
            <h1 class="title is-2"><i class="fas fa-globe-americas"></i> Intro</h1>
              <p><i class="fas fa-book"></i> <%= @user.bio %></p>
          </div>
        </div>
        <% if user_signed_in? && @user == current_user %>
          <div class="column is-three-fifths">
            <div class="post-form">
              <%= simple_form_for @post do |f| %>
                <%= f.text_area :text, label: 'name', placeholder: 'what\'s in your mind?', class:"textarea post-area" %>
                <div id="image-upload-js" class="file has-name">
                  <label class="file-label">
                    <%= f.file_field :image, class: 'file-input' %>
                    <span class="file-cta">
                      <span class="file-icon">
                        <i class="fa fa-image"></i>
                      </span>
                      <span class="file-name has-text-grey-light">
                        No file uploaded
                      </span>
                    </span>
                  </label>
                </div>
                <%= f.button :submit, 'Post' ,class: 'button is-medium btn-base' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="posts-container">
        <% if @posts.empty? %>
          <p class="note">There is no posts, availble here.</p>
        <% end %>
        <% @posts.each do |post| %>
          <div id="post-<%= post.id %>" class="box">
            <div class="poster-identifier">
              <div class="poster-info">
                <%= link_to user_path(@user) do %>
                  <div class="image-wrapper">
                    <%= render partial: 'user_image', locals: { user: @user } %>
                  </div>
                <% end %>
                <div class="post-data">
                  <%= link_to user_path(@user), class: "has-text-black underline" do %>
                    <span class="name"><%= @user.username %></span>
                  <% end %>
                  <span class="username">@<%= @user.username %></span>
                  <span class="date">
                    <%= time_ago_in_words(post.created_at) %>
                  </span>
                </div>
              </div>
              <% if current_user == post.user %>
                <div class="post-actions">
                  <div class="dropdown">
                    <div class="dropdown-trigger">
                      <a class="post-action-container"><i class="fas fa-ellipsis-v"></i></a>
                    </div>
                    <div class="dropdown-menu" id="dropdown-menu4" role="menu">
                      <div class="dropdown-content post-action-menu">
                      <%= link_to  "Edit", edit_post_path(post), class: "dropdown-item" %>
                      <%= link_to  "Delete", post_path(post), method: :delete, class: "dropdown-item" %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>

            <div class="post-text">
              <%= post.text %>
            </div>

            <% if post.image.attached? %>
              <div class="post-image">
                <%= image_tag post.image %>
              </div>
            <% end %>

            <div class="comments-container">
              <% post.comments.each do |comment| %>
                <%= render partial: 'comments/comment', locals: { post: post, comment: comment } %>
              <% end %>
            </div>

            <% if user_signed_in? %>
              <div class="comment-form">
                <div class="comment-avatar">
                  <%= render partial: 'user_image', locals: { user: current_user } %>
                </div>
                <%= simple_form_for current_user.comments.new, url: post_comments_path(post) do |f| %>
                  <%= f.text_area :text, placeholder: 'what\'s in your mind?', class: "textarea"%>
                  <%= f.button :submit, 'Comment', class: 'button is-success is-small' %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>